=== tyyna/contactbook_manager/ContactBook/src/main/java/fi/muni/cz/convertor/contacts.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">

<xsd:element name="contacts" type="contactsType">
  <xsd:key name="contactKey">
    <xsd:selector xpath="contact" />
    <xsd:field xpath="@cid" />
  </xsd:key>
</xsd:element>

<xsd:complexType name="contactsType">
  <xsd:sequence>
    <xsd:element name="contact" type="contactType" minOccurs="1" maxOccurs="unbounded"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="contactType">
  <xsd:sequence>
    <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
    <xsd:element name="surname" type="xsd:string" minOccurs="1" maxOccurs="1"/>
    <xsd:element name="info" type="infoType" minOccurs="1" maxOccurs="1"/>
  </xsd:sequence>
  <xsd:attribute name="cid" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="infoType">
  <xsd:sequence>
    <xsd:element name="address" type="addressType" minOccurs="0" maxOccurs="1"/>
    <xsd:element name="emails" type="emailsType" minOccurs="0" maxOccurs="1"/>
    <xsd:element name="phones" type="phonesType" minOccurs="0" maxOccurs="1"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="addressType">
  <xsd:sequence>
    <xsd:element name="street" type="xsd:string" minOccurs="1" maxOccurs="1"/>
    <xsd:element name="number" type="xsd:string" minOccurs="1" maxOccurs="1"/>
    <xsd:element name="city" type= "xsd:string" minOccurs="1" maxOccurs="1"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="emailsType">
  <xsd:sequence>
    <xsd:element name="email" type="emailType" minOccurs="1" maxOccurs="unbounded"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:simpleType name="emailType">
  <xsd:restriction base="xsd:string">
    <xsd:pattern value=".*[a-zA-Z]+.*[@].*[a-zA-Z]+.*"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="phonesType">
  <xsd:sequence>
    <xsd:element name="phone" type="phoneType" minOccurs="1" maxOccurs="unbounded"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:simpleType name="phoneType">
  <xsd:restriction base="xsd:integer">
    <xsd:pattern value="[0-9]{9}"/>
  </xsd:restriction>
</xsd:simpleType>

</xsd:schema>

=== tyyna/contactbook_manager/javaMaven/src/main/java/fi/muni/cz/contacts/contacts_sample.xml
<?xml version="1.0" encoding="UTF-8"?>

<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="contacts.xsd">
  <contact cid="1">
    <name>Jan</name>
    <surname>Novák</surname>
    <info>
      <address>
        <street>Skorkovského</street>
        <number>několik</number>
        <city>Brno</city>
      </address>
      <emails>
        <email>jan.novak@gmail.com</email>
        <email>novak.jan@gmail.com</email>
      </emails>
      <phones>
        <phone>123456789</phone>
      </phones>
    </info>
  </contact>
  <contact cid="2">
    <name>Pavel</name>
    <surname>Novotný</surname>
    <info>
      <address>
        <street>Kaštanová</street>
        <number>3</number>
        <city>Brno</city>
      </address>
      <emails>
        <email>pavel.novotny@gmail.com</email>
        <email>novotny.pavel@gmail.com</email>
      </emails>
      <phones>
        <phone>987645321</phone>
      </phones>
    </info>
  </contact>
  <contact cid="3">
    <name>Kamila</name>
    <surname>Nová</surname>
    <info>
    </info>
  </contact>
</contacts>
